import { z } from "zod";
import { composeTasks } from "./generator.js";

export const composeInputSchema = z.object({
  taskType: z.enum(composeTasks),
  managedClearEnvironmentKeys: z.array(z.string().regex(/^[A-Z][A-Z0-9_]*$/)).max(100).optional(),
  managedPortAction: z.enum(["add", "replace", "remove"]).optional(),
  managedOriginalBinding: z.object({ address: z.string().max(255), port: z.string().regex(/^\d{1,5}$/) }).strict().optional(),
  gluetunServiceName: z.string().max(128).optional(),
  gluetunContainerName: z.string().max(128).optional(),
  composeProjectName: z.string().max(128).optional(),
  externalNetworkName: z.string().max(128).optional(),
  useEnvFile: z.boolean().optional(),
  provider: z.string().max(80).optional(),
  vpnType: z.enum(["wireguard", "openvpn"]).optional(),
  anyLocation: z.boolean().optional(),
  countries: z.string().max(500).optional(),
  regions: z.string().max(500).optional(),
  cities: z.string().max(500).optional(),
  hostnames: z.string().max(2_000).optional(),
  serverNames: z.string().max(2_000).optional(),
  categories: z.string().max(500).optional(),
  isps: z.string().max(500).optional(),
  providerOptions: z.record(z.string().regex(/^[A-Z][A-Z0-9_]*$/), z.string().max(128)).optional(),
  authMode: z.enum(["none", "api_key", "basic"]).optional(),
  apiKey: z.string().max(4096).optional(),
  basicUsername: z.string().max(256).optional(),
  basicPassword: z.string().max(4096).optional(),
  wireguardPrivateKey: z.string().max(4096).optional(),
  wireguardAddresses: z.string().max(1024).optional(),
  wireguardPresharedKey: z.string().max(4096).optional(),
  wireguardPublicKey: z.string().max(4096).optional(),
  wireguardEndpointIp: z.string().max(64).optional(),
  wireguardEndpointPort: z.number().int().min(1).max(65_535).optional(),
  openvpnUser: z.string().max(4096).optional(),
  openvpnPassword: z.string().max(4096).optional(),
  openvpnCertificate: z.string().max(65_536).optional(),
  openvpnKey: z.string().max(65_536).optional(),
  openvpnEncryptedKey: z.string().max(65_536).optional(),
  openvpnKeyPassphrase: z.string().max(4096).optional(),
  customOpenvpnConfigPath: z.string().max(1024).optional(),
  routingScope: z.enum(["same_project", "separate_project"]).optional(),
  appName: z.string().max(120).optional(),
  appImage: z.string().max(500).optional(),
  hostAddress: z.string().max(255).optional(),
  hostPort: z.number().int().min(1).max(65_535).optional(),
  containerPort: z.number().int().min(1).max(65_535).optional(),
  protocol: z.enum(["tcp", "udp"]).optional(),
  pastedCompose: z.string().max(1_048_576).optional(),
  includeSecrets: z.boolean().optional()
}).strict();
